---
title: "Example_Run"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example_Run}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
Sys.setenv("GITHUB_PAT" = "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")
devtools::install_github('GabPescador/gRNASelect',
                         auth_token = Sys.getenv("GITHUB_PAT"))
library(gRNASelect)
# It is not loading the packages that it depends on, will have to check how to fix this
```

# Loading tables and filtering based on ATGC content
```{r}
# Input file comes from the design module: https://github.com/hzuzu/gRNADesign
x <- RNAFoldOutput

df_melt <- reshape2::melt(x, measure.vars = c("Average_score", "G_Percentage", "C_Percentage", "A_Percentage", "T_Percentage"))
  
  df_melt %>%
    filter(!variable == "Average_score") %>%
    ggplot(aes(x=variable, y=value)) +
    geom_boxplot() +
    annotate(geom="text",
             y=max(filter(df_melt, !variable == "Average_score")[,"value"]),
             x=c(1,2,3,4),
             hjust=0.5,
             label=c(paste0("mean = ", round(mean(filter(df_melt, variable == "G_Percentage")[,"value"]),2)),
                     paste0("mean = ", round(mean(filter(df_melt, variable == "C_Percentage")[,"value"]),2)),
                     paste0("mean = ", round(mean(filter(df_melt, variable == "A_Percentage")[,"value"]),2)),
                     paste0("mean = ", round(mean(filter(df_melt, variable == "T_Percentage")[,"value"]),2)))) +
    annotate(geom="text",
             y=min(filter(df_melt, !variable == "Average_score")[,"value"]),
             x=0.5,
             hjust=0,
             label=paste0("n = ",nrow(df))) +
    theme_classic() +
    xlab("") +
    ylab("Percentage (%)") +
    ggtitle("ATGC")

# Plotting ATGC % before filtering
gRNAatgcPlot(x)

# Plotting RNA Fold Scores before filtering
gRNAScorePlot(x)

# Perform filtering based on ATGC%
# Defaults are 15:35% range, but can be modified to any range of numbers
y <- gRNAatgcFilter(x)

# Plots after filtering
gRNAatgcPlot(y)
gRNAScorePlot(y)

# all plots together
cowplot::plot_grid(plotlist = list(gRNAatgcPlot(x), gRNAatgcPlot(y),
                                   gRNAScorePlot(x), gRNAScorePlot(y)))

# Checking how many gRNAs per gene
gRNAperGene(y)

# Checking transcript regions
gRNAutrperGene(y)
```

# Select gRNAs based on Scores
```{r}
# gRNASelection can define how many gRNAs you select based on RNAFold scores
# It always selects the top and the bottom scores + a random selection of gRNAs
# per transcript
# type2 column specifies criteria for choice of gRNA
newgRNAs <- gRNASelection(y, minN = 10, randomN = 8)

# Ploting after selection
gRNAatgcPlot(newgRNAs)
gRNAScorePlot(newgRNAs)
gRNAutrperGene(newgRNAs)
# note that if all gene have enough gRNAs, the histogram should only have data in n = 10 for the default settings
```

# Filter mismatches
```{r}
# Input file comes from the mismatch module: https://github.com/hzuzu/gRNADesign
# Requires a folder with all mismatches per gRNA and keeps only gRNAs with
# >4 mismatches to any transcript
z <- gRNAmismatchFilter(path = system.file("data/output_mismatches",
                                           "",
                                           package = "gRNASelect"),
                        data = newgRNAs)

# Splits all selected gRNAs into tables for IDT ordering in 96-well format
# Defaults to 3 gRNAs per gene, but can be changed with nmax
gRNA96well(z, outputpath = "./")
```

